### ISSUE TITLE
Viewing submitted transaction in transaction history should open that specific transaction

### ISSUE THREAD

**Issue by CyrusVorwald-ICON** [icon-project/Nexus#704]
**Is your feature request related to a problem? Please describe.**
It's too difficult to find my transaction in the transfer history after submitting a transaction, particularly if many people are using Nexus at the same time.

**Describe the solution you'd like**
The transaction submitted successfully popup should be of that transaction in the history. Rather than this page

<img width="486" alt="image" src="https://user-images.githubusercontent.com/90732384/187307688-d150a195-11ad-413e-a922-7428bb5b389b.png">

Take me to this page

<img width="833" alt="image" src="https://user-images.githubusercontent.com/90732384/187307729-fe12c999-2baf-48b7-aed5-c4b4aac71b8d.png">

**Describe alternatives you've considered**

- [ ]  "View on Transaction History" button goes directly to that transaction in the history, rather than the entire history page. This still adds an extra step for what someone would want to do.

- [ ] Transaction history by default filters to the connected source wallet. This should also be done separately. https://github.com/icon-project/Nexus/issues/716

**Comment by duyphanz** [comment]
I'd prefer the alternatives. There is a case when a tx is submitted successfully, BE side will take some time for syncing the block including that tx, then save it to the database as a record. If the user tries to view tx details at that time, we will display a message `Your transaction is being synced or not found. Please try again later.`

<img width="812" alt="image" src="https://user-images.githubusercontent.com/13731780/190337943-879e4c61-0cab-4709-8a85-e9e2a72815ee.png">

Otherwise, it works properly.

**Comment by duyphanz** [comment]
deployed to https://testnet.nexusportal.io/
